# Generated by Django 5.0.4 on 2024-04-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userchat_group_name_alter_userchat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='member_name',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
